apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
     app: httpbin
spec:
  type: ClusterIP
  selector:
    app: httpbin
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP